[build]
  publish = "."

[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"

[[headers]]
  for = "/models/*.glb"
  [headers.values]
    Content-Type = "model/gltf-binary"
